### ISSUE TITLE
How to disable symbol conversion?

### ISSUE THREAD

**Issue by tylerlmz1** [xypnox/xydark-typora#1]
when typing something like `<=`, it would convert it to `≤`

this can be troubling for my source code in some programming languages, I can't be sure what the original symbol is

I tried digging into the theme's source code, and can't figure out how to disable it, thinking it might be just how the .ttf file is, and can't be easily disabled

I really like this theme and am not ready to use another theme without trying to fix this first, do you know how to disable it? or is it not easily possible?

Thanks for your time and effort into this theme.

**Comment by xypnox** [comment]
Hi, the ligatures are provided by the font named Iosevka.

They can be disabled through css `font-variant-ligatures: none;`.
I will try to create a variant with ligatures disabled. I hope this will solve the issue!

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

**Comment by tylerlmz1** [comment]
yes it worked!
thank you so much!

**Comment by xypnox** [comment]
I am glad! Thanks for reaching out!
